export const PUZZLE_QUIZ_PLATEONE = "PUZZLE_QUIZ_PLATEONE";
export const PUZZLE_QUIZ_PLATETWO = "PUZZLE_QUIZ_PLATETWO";
export const PUZZLE_QUIZ_PLATETHREE = "PUZZLE_QUIZ_PLATETHREE";
export const PUZZLE_QUIZ_PLATEFOUR = "PUZZLE_QUIZ_PLATEFOUR";
export const PUZZLE_QUIZ_PLATEFIVE = "PUZZLE_QUIZ_PLATEFIVE";
